# This is a basic workflow that is manually triggered

name: Cypress E2E Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cypress-run"
  cypress-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # define how to checkout the source code
    - name: Checkout
      uses: actions/checkout@v2.5.0
    # define Cypress parameters 
    - name: Cypress.io
      uses: cypress-io/github-action@v4.2.0
      # with: start a test environment
      # with: 
      #  start: npm start
